name: "E2E: Automation suite"
on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select test suite to run'
        default: 'regression'
        required: true
        type: choice
        options:
          - regression
          - sanity
          - smoke

permissions:
  contents: read
  statuses: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          ref: ${{ github.sha }}

      - name: test
        id: test
        run: |
          mkdir -p /tmp/reports
          echo "bruh" > /tmp/reports/bruh.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: /tmp/reports/

  test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          ref: ${{ github.sha }}

      - name: test2
        id: test2
        run: |
          cat /tmp/reports/bruh.txt || exit 0


      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: test
          path: /tmp/reports/

      - name: test3
        id: test3
        run: |
          cat /tmp/reports/bruh.txt
